updating akka and kafka versions
pagopa/pdnd-interop-uservice-party-management pull request #137
Opened 2022-07-27 10:51 UTC by andrea-putzu

Avoiding "Could not initialize class reactor.netty.http.client.HttpClientSecure" error

2022-07-27 10:55 UTC, galales requested changes

2022-07-27 10:55 UTC, galales commented on build.sbt
> +val AkkaVersion = "2.6.18"
```suggestion
```
this is already defined in `project/Versions.scala`

2022-07-27 10:55 UTC, galales commented on build.sbt
> +        "com.typesafe.akka" %% "akka-stream" % AkkaVersion
```suggestion
        "com.typesafe.akka" %% "akka-stream" % akkaVersion
```

2022-07-27 10:55 UTC, galales commented on build.sbt
> +val KafkaVersion = "3.0.0"
for consistency I suggest to move this value to `project/Versions.scala`

2022-08-02 13:38 UTC, andrea-putzu commented
does the fix is ok?

2022-08-02 13:40 UTC, TonioGela requested changes

2022-08-02 13:40 UTC, TonioGela commented on project/Versions.scala
> +  lazy val kafkaVersion             = "2.1.1"
```suggestion
  lazy val akkaStreamKafkaVersion             = "2.1.1"
```

2022-08-02 13:40 UTC, TonioGela commented on build.sbt
> +        "com.typesafe.akka" %% "akka-stream-kafka" % kafkaVersion % Compile,
```suggestion
        "com.typesafe.akka" %% "akka-stream-kafka" % akkaStreamKafkaVersion % Compile,
```

2022-08-02 13:40 UTC, TonioGela commented on build.sbt
> +import Versions.{akkaVersion, kafkaVersion}
```suggestion
import Versions.{akkaVersion, akkaStreamKafkaVersion}
```

2022-08-02 14:28 UTC, merged