Payload & new Relationship State
pagopa/pdnd-interop-uservice-party-management pull request #146
Opened 2022-10-11 16:42 UTC by andrea-putzu

2022-10-11 21:29 UTC, TonioGela requested changes

2022-10-11 21:29 UTC, TonioGela commented on src/main/resources/application.conf
> +  send-mail-to-institute = ${}
This won't compile

2022-10-13 14:58 UTC, galales approved these changes

2022-10-14 07:54 UTC, TonioGela approved these changes

2022-10-14 10:00 UTC, merged